// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDw9COH2vjIKBqhYN6WL4aKCS1fTNbGt2I',
    appId: '1:842334742561:web:8f296cb7c264494a611b60',
    messagingSenderId: '842334742561',
    projectId: 'mtnno1-65b5c',
    authDomain: 'mtnno1-65b5c.firebaseapp.com',
    storageBucket: 'mtnno1-65b5c.appspot.com',
    measurementId: 'G-JDEGQ0XLP7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCXjBENLDXWUHQTMSOkXheNWdBaAxJYFL8',
    appId: '1:842334742561:android:4d2efa491e874144611b60',
    messagingSenderId: '842334742561',
    projectId: 'mtnno1-65b5c',
    storageBucket: 'mtnno1-65b5c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBUIJowrbTQCF297-oxwWhAsEScp-CnenU',
    appId: '1:842334742561:ios:2e5b6f34037cf97c611b60',
    messagingSenderId: '842334742561',
    projectId: 'mtnno1-65b5c',
    storageBucket: 'mtnno1-65b5c.appspot.com',
    iosBundleId: 'com.example.mtnno1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBUIJowrbTQCF297-oxwWhAsEScp-CnenU',
    appId: '1:842334742561:ios:2e5b6f34037cf97c611b60',
    messagingSenderId: '842334742561',
    projectId: 'mtnno1-65b5c',
    storageBucket: 'mtnno1-65b5c.appspot.com',
    iosBundleId: 'com.example.mtnno1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDw9COH2vjIKBqhYN6WL4aKCS1fTNbGt2I',
    appId: '1:842334742561:web:acc350cbd6044f2e611b60',
    messagingSenderId: '842334742561',
    projectId: 'mtnno1-65b5c',
    authDomain: 'mtnno1-65b5c.firebaseapp.com',
    storageBucket: 'mtnno1-65b5c.appspot.com',
    measurementId: 'G-R37NLDZMS0',
  );
}
